### ISSUE TITLE
More imagery needed

### ISSUE THREAD

**Issue by AtheistApe** [MyCodeSnips/Rainbow-Poem#4]
Hello,

I think more imagery is needed for the poem. Lines that bring images to the mind such as:

Arcs of colored light painted on the sky
![image](https://cloud.githubusercontent.com/assets/21245221/18008136/ccdec206-6b5b-11e6-9624-3adb8ecbce02.png)

**Comment by MyCodeSnips** [comment]
Thank you, I added some changes. What do you think of them?

**Comment by AtheistApe** [comment]
Looks good. I think that fixes the problem
